/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.22).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.SmallInfo;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.bind.annotation.CookieValue;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2020-11-07T19:30:51.910Z[GMT]")
@Api(value = "goals", description = "the goals API")
public interface GoalsApi {

    @ApiOperation(value = "", nickname = "getGoals", notes = "", response = SmallInfo.class, responseContainer = "List", tags={ "goals", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = SmallInfo.class, responseContainer = "List"),
        @ApiResponse(code = 401, message = "Authentication information is missing or invalid") })
    @RequestMapping(value = "/goals",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<SmallInfo>> getGoals(@ApiParam(value = "" ) @RequestHeader(value="Auth", required=false) String auth
);

}

