name: Docker image

on:
  push:
    branches: [ feature/AutoBuild ]
  pull_request:
    branches: [ feature/AutoBuild ]
jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build /home/cbi/actions_runner/_work/Junction2020Connected/Junction2020Connected/BackEnd/target/swagger-spring-1.0.1.jar --file BackEnd/target/Dockerfile --tag realityfamily/dockervm:javaback$(date +%s)