name: Docker image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: mvn -B package --file BackEnd/pom.xml && docker build BackEnd/target --file BackEnd/target/Dockerfile --tag realityfamily/dockervm:javaback && docker push realityfamily/dockervm:javaback

